backend = "glx";
vsync = true;

# Sharp Corners
corner-radius = 0;
round-borders = 1;

# Shadows / Glow
# shadow = true;
# shadow-radius = 18;
# shadow-opacity = 0.55;
# shadow-offset-x = -15;
# shadow-offset-y = -15;
# shadow-color = "#7B52C4";

# Exclude Eww from shadows so future widgets don't render double-borders (ts no work)
# shadow-exclude = [
#   "window_type = 'dock'",
#   "class_g = 'qtile'",
#   "class_g = 'Qtile'"
# ];



# Animations 
animations = true;
animation-stiffness = 300;
animation-window-mass = 1.0;
animation-dampening = 26;
animation-clamping = true;

# Exclude Wired from the global CRT zoom effect
#animation-exclude = [
#  "class_g = 'Wired'",
#  "class_g = 'wired'"
#];
#wintypes:
#{
#  # Make notifications slide in perfectly on the X-axis from the right
#  notification = {
#    animation-for-open-window = "slide-in";
#
#    };
#};
# Windows snap open rapidly
animation-for-open-window = "zoom";


# Whatever the fuck this is. If they are disabled/outcommented it WORKS, if they actually apply, not.
animation-for-unmap-window = "zoom"; 
animation-for-workspace-switch-in = "zoom";
animation-for-workspace-switch-out = "zoom";


# Glass / BLur stuff
# dual_kawase is the best looking, most performant blur method for modern picom, apparently
blur-method = "dual_kawase";

# Blur strength (1-20)
blur-strength = 8;

# Apply blur to transparent windows like Alacritty
blur-background = true;

# Exclude things that shouldn't be blurred (like the bar or tooltips) (this dont work btw)
blur-background-exclude = [
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];